#Ex-11
X=matrix(c(1,0,2,5,3,1,1,3,1,3,3,1,0,2,2,1,0,2,1,0),nrow=4)
print(X)
print(rownames(X))
print(colnames(X))
rownames(X)=rownames(X,do.NULL=FALSE,prefix='Trial')
print(rownames((X)))
print(X)
drugs=c('aspirin','paracetamol','nurofen','palacebo','hedex')
colnames(X)=drugs
print(colnames(X))
print(X)
dimnames(X)=list(NULL,paste("drug",1:5,sep="")) #Changes in column names
print(X)

#Ex12
print(mean(X[,5]))
print(var(X[4,]))
print(rowSums(X))
print(colSums(X))
print(apply(X,1,sum))
print(apply(X,2,sum))
print(rowMeans(X))
print(colMeans(X))
print(apply(X,1,mean))
print(apply(X,2,mean))
print(apply(X,2,sqrt))
print(apply(X,2,function(X)X^2+X))
group=c("A","B","B","A")
print(rowsum(X,group))
print(row(X))
print(col(X))
print(tapply(X,list(group[row(X)], col(X)),sum))
print(aggregate(X,list(group),sum))